<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

use App\Models\QuizDomainValueAnswerValuation;

use App\Models\QuizDomainValue;

use Illuminate\Support\Arr;

class QuizDomainValueAnswerValuationTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
      $data = [
        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Intellectual stimulation")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated intellectual stimulation as being of low importance <br><br> This may mean that you would favour a role that has clearly defined processes and proceedures  which provide a high level of predictability.", 'moderateSentence' => "Intellectual Stimulation is moderate value for you. This means that although it is important to you it is not one of your top values.<br><br>It will be important to work in a role that requires a moderate level of critical thinking, learning and creative problem solving.", 'highSentence' => "You rated Intellectual Stimulation as being of high importance to you. <br><br> It will be important for you to look for roles that enable you to use your intellect to achieve results.<br><br>You value work that provides you with the opportunity to think independently, learn new things and be involved in innovation, critical thinking and creative problem solving."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Recognition")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated Recognition as being of low importance. <br><br> You may be primarily motivated from instrinic motivators such as doing a good job, developing mastery or helping others.", 'moderateSentence' => "Recognition is moderate value for you. This means that although it is important to you, you are also motivated by intrinsic motivators such as doing a good job, creating something new or seeing how your work has a positive impact on the lives of others.<br><br>It will be important to work in a role that provides you with a moderate level of recognition that you can use to motivate you alongside your other more intrinsic motivators.", 'highSentence' => "You rated Recognition as being of high importance to you.<br><br>You value work where you have the opportunity to receive acknowledgement or respect for both the effort you have put in, and the results that you have achieved.<br><br>It will be important for you to work in an environment where you will be able to gain recognition or status for your contribution."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Achievement")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated achievement as being of low importance.<br><br>This may mean that you are motivated by others factors such as creativity, independence or altruism.", 'moderateSentence' => "Achievement is moderate value for you. This means that although it is important to you, you are also motivated by being involved in the actual process of work for example creating something new, innovating or interacting with others.<br><br>It will be important to work in a role that provides you with a moderate level of achievement balanced with the type of work that you enjoy.", 'highSentence' => "You rated Achievement as being of high importance to you.<br><br>You value developing new skills or achieving targets.<br><br>It is important that you are in role where you can gain a sense of achievement through setting goals, working hard and achieving results.<br><br>A work environment that recognises achievement in both the short term and the long term will provide you with a sense of satisfaction and progress."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Independence")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated independence as being of  low importance.<br><br>This may mean that you would be happier working in an office with a team rather than remote working. It could also mean that you would prefer not to have to make decisions but would rather follow a predetermined set of processes and proceedures.", 'moderateSentence' => "Independence is moderate value for you. This means that although it is important to you, you also like either following a set process or working as part of team towards a common goal.<br><br>It will be important to work in a role that provides you with a moderate level of independence – for example choice on where you complete your work – balanced with a factors such predictability around processes or working as part of a larger team.", 'highSentence' => "You rated Independence as being of high importance to you.<br><br>You value being able to make decisions on issues such as how you approach a task, how you prioritise your workload or diary and where and when you choose to carry out your work.<br><br>It will be important for you to work in a role with a high level of independence and autonomy."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Variety")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated variety of being of low importance.<br><br>This may mean that you value having a set of predictable tasks or following clearly defined proceedures. It may also mean that you would rather focus on one very specific problem or specialist role.", 'moderateSentence' => "Variety is moderate value for you. This means that although it is important to you, you also like a certain level of consistency or predictability in your role.<br><br>It will be important to work in a role that provides you with a moderate level of variety – for example being involved in range of projects – balanced with consistency and predictability of what is expected of you.", 'highSentence' => "You rated Variety as being of high importance to you.<br><br>This may come from having a role that involves a range of diverse tasks, settings, client groups or from learning new things."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Security")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated Security as being of low importance.<br><br>This may mean that other values such as creativity and independence are more important to you and that you value opportunties for taking risks and growth above a secure job.", 'moderateSentence' => "Security is moderate value for you. This means that although it is important to you, you also can tolerate a certain level of uncertainty if it enables you to experience new opportunities or career progression.<br><br>It will be important to work in a role that provides you with a moderate level of security – for example having a consistent wage – balanced with factors such as opportunities for growth or taking on new roles within the organisation.", 'highSentence' => "You rated Security as being of high importance to you.<br><br>You value knowing that you have a job with a high level of security, despite fluctuations in the job market or economy. This includes clarity about the work necessary to enhance your job security.<br><br>It is important to you to have a role that provides you with security through a permanent contract."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Way of Life")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated Way of Life as being of low importance to you.<br><br>It may be that you are willing to work hard in a role with long hours for achievement, security or altruism.", 'moderateSentence' => "Way of Life is moderate value for you. This means that although it is important to you, you are willing to make some sacrifices in the early part of your career to build up your experience or progress in an organisation.<br><br>It will be important to work in a role that provides you with a moderate work life balance – for example having consistent working hours – balanced with opportunities to take on extra work for experience or financial gain.", 'highSentence' => "You rated Way of Life as being of high importance to you.<br><br>You value being able to balance your working life with your personal life through a job that provides you with the means and the flexibility to pursue a range of interests in your own time.<br><br>It is important to you to have a job that allows you to lead the type of lifestyle that you choose."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Surroundings")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated Surroundings as being of low importance to you.<br><br>This may means that you are willing to sacrifice a comfortable or pleasant working environment for other factors such as flexibility, achievement or security.", 'moderateSentence' => "Surroundings is a moderate value for you. This means that although the quality of the environment that you work in is important to you, other factors may be more important such as variety in your role or opportunity for higher economic return.<br><br>It will be important to work in a role that provides you with pleasant surroundings balanced with the other values that help you thrive in work.", 'highSentence' => "You rated Surroundings as being of high importance to you.<br><br>It is very important to you that you work in an environment which is pleasant and suited to your preferences.<br><br>For example, you may prefer to work outside, in a quiet environment where you can concentrate without distraction or value having the flexibility to choose where and when you complete your work. You also value having equipment that is fit for purpose."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Economic Return")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated Economic Return as being of low importance to you.<br><br>This may be because other factors such as security, way of life or independence are more important to you.", 'moderateSentence' => "Economic Return is a moderately important value for you. This means that although it is important that you receive a fair wage which enables you to meet your needs, other factors are more important to you – this might be the type of work you carry out, freedom of choice about where you work or the overall purpose of your work.<br><br>It will be important to work in a role that provides you with a good wage balanced with the other values that help you thrive in work.", 'highSentence' => "It is important to you that your job pays well and provides you with the opportunity to have a good standard of living.<br><br>This may include working in an organisation that provides a clear path of progression so that you have opportunities to enhance your salary as you gain skills, experience and qualifications."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Altruism")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => 'You rated Altruism as low importance to you.<br><br>You may be more motivated by factors such as intellectual stimulation or creativity.', 'moderateSentence' => "Altruism is a moderately important value for you.<br><br>It will be important for you to have opportunties within your role to help others or to feel that your work is positively contributing to the lives of others.", 'highSentence' => "It is important to you to contribute to the welfare of others.<br><br>You value being in a position where your work leads to positive outcomes for others and enhances their lives."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Supervisory Relationship")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated having a positive relationship with your supervisors as of low importance to you.<br><br>This may be because you would like to start your own business or in a role with a high level of independence.", 'moderateSentence' => "Your relationship with your supervisory is a moderately important value for you. This means that although it is important that you to have a good relationship with your supervisor or manager, you are flexible and other factors such as Way of Life and Intellectual Stimulation may be more important.<br><br>It will be important to work in a role where you have a good relationship with your supervisor but also opportunities to ensure you are meeting you most important values.", 'highSentence' => "You rated Supervisory Relationship as being of high importance to you.<br><br>It is very important to you to have a good relationship with your line manager or supervisor.<br><br>Having a manager who is approachable, fair and who values your contribution means that you will be motivated to do your best at work."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Associates")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated a good relationship with Associates as being of low importance to you.<br><br>This may mean that you would thrive in a role that require sole working or a high level of independence.", 'moderateSentence' => "Your relationship with your associates is a moderately important value for you. This means that although it is important that you have a good relationship with your associates or colleagues, you are also happy to work with a range of people or independently.<br><br>It will be important to work in a role where you have opportunities to carry out both work with a team and independently.", 'highSentence' => "You rated Associates as being of high importance to you.<br><br>It is very important for you to work as part of a team, and you thrive when working with others towards a common goal.<br><br>You like to have a positive relationship with your colleagues and have opportunities to interact with them on a regular basis."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Belonging")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated Belonging as being of low importance to you.<br><br>This may be because you would prefer to work in a role with a high level of independence.", 'moderateSentence' => "Belonging is a moderately important value for you. This means that although it is important for you to have a sense of belonging with a team or organisation, other values are more important, and you may be equality comfortable working on your own.<br><br>It will be important to work in a role where you have opportunities to carry out both work with a team and independently.", 'highSentence' => "You rated Belonging as being of high importance to you.<br><br>It is very important for you to have a sense of belonging to the organisation that you work for.<br><br>This is enhanced in organisations who have a clear sense of purpose that you believe in and values their individual employees."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Family")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rate Family as being of low importance to you.<br><br>You feel free to make decisions about your career without having to worry about making your family proud or providing for them.", 'moderateSentence' => "You rated Family as being of moderate importance to you.<br><br>It is important that you have a career that benefits your family or makes them proud, however this is not as important as the values that you rated highly.", 'highSentence' => "You rated Family as being of high importance to you.<br><br>It is important to you to have a career that your family would approve of and be proud of and that would bring benefits to your family as well as to yourself."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Aesthetic")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You value Aesthetics as being of low importance to you.<br><br>This may be that you value functionality or clearly defined processes as being more important than creating beauty.", 'moderateSentence' => "Creating art or beautiful products or environments is a moderately important value for you. This means that although Aesthetics is important to you, other values are more important for examples intellectual stimulation or altruism.<br><br>It will be important to work in a role where you have opportunities to add to beauty if it is relevant to do so.", 'highSentence' => "You rated Aestetic as being of high importance to you.<br><br>It is very important for you to be involved in work that creates beauty, designs beautiful products, or creates beautiful spaces or landscapes for people to enjoy.<br><br>You would thrive in an environment that values aesthetics and where you are given the opportunity to use your artistic skills to create beauty through the work that you do."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Creativity")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated Creativity as being of low importance to you.<br><br>This may be because you would prefer a role with clearly defined processes, tasks or proceedures.", 'moderateSentence' => "Creativity is a moderately important value for you.<br><br>It is important that you find a role that enables you to have a level of creativity. Creativity is valuable in a wide variety of tasks including construction, design, or finding innovative solutions to complex problems.", 'highSentence' => "It is very important for you to be creative.<br><br>You work best when you are free to be creative. This may involve solving difficult problems, creating new products, looking at an issue from different angles or creating innovative solutions.<br><br>You understand that the creative process needs space to thrive, and you value environments that enables you to work in this way rather than sticking to specific rules or processes."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Leadership")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated Leadership as being of low importance to you.<br><br>You may prefer to be a role that does not require you to take the lead or to manage people.", 'moderateSentence' => "Leadership is a moderately important value for you.<br><br>It will be important for you to have a role that provides you with some opportunities for leadership or the prospects of working towards a leadership role in the future. Leadership does not always require people management; it can also mean taking the lead in a project or planning and strategy development.", 'highSentence' => "It is very important for you to have opportunities to take on a leadership role.<br><br>This may be through leading others, taking on responsibility for specific projects or developing strategies."],

        ["quiz_domain_value_id" => QuizDomainValue::where('title', "Protecting the Planet")->first()->id, "low" => [0, 3], "moderate" => [4, 7], 'high' => [8, 12],'lowSentence' => "You rated Protecting the Planet as being of low importance to you.<br><br>This might mean that other factors such as achievement, intellectual stimulation or economic return are more motivating for you.", 'moderateSentence' => "Protecting the Planet is a moderately important value for you.<br><br>This may mean that it will be important for you to work for a company that takes it's responsibility for operating in a sustainable manner, seriously.", 'highSentence' => "Protecting the Planet is an important value for you.br><br>It is important that you work for an organisation that takes its responsibility for the planet seriously.<br><br>Roles that enable you to live and work in a sustainable way or facilitate you to actively protect the planet will align with your values."]
      ];

      foreach ($data as $key => $value) {

        QuizDomainValueAnswerValuation::updateOrCreate($value);

      }

    }
}
